name: TR_Smoke

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Run tests
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HTTP_PROXY: http://63.32.1.88:80
      HTTPS_PROXY: http://63.32.1.88:80
      NO_PROXY: "localhost,127.0.0.1"

    steps:
    - name: Install CA certificates
      run: sudo apt-get install -y ca-certificates

    - name: Configure Git to use proxy and CA certificates
      run: |
        git config --global http.proxy $HTTP_PROXY
        git config --global https.proxy $HTTPS_PROXY
        git config --global http.sslCAInfo /etc/ssl/certs/ca-certificates.crt
        git config --global https.sslCAInfo /etc/ssl/certs/ca-certificates.crt


    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

      # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Configure playwright
      run: playwright install

    - name: Run tests
      if: "github.event.inputs.deployment_target == 'Run tests'"
      run: pytest test_tr_smoke.py

