name: TR_Smoke

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Run tests
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Configure playwright
      run: playwright install

    # Set up proxy
    - name: Set up proxy
      env:
        HTTP_PROXY: http://kbc:347SP&Uwqt!2xZ7w@138.197.150.103:8090
        HTTPS_PROXY: http://kbc:347SP&Uwqt!2xZ7w@138.197.150.103:8090
      run: |
        echo "HTTP_PROXY=$HTTP_PROXY" >> $GITHUB_ENV
        echo "HTTPS_PROXY=$HTTPS_PROXY" >> $GITHUB_ENV

    - name: Run tests
      if: "github.event.inputs.deployment_target == 'Run tests'"
      run: pytest test_tr_smoke.py

