name: TR_Smoke

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Run tests
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

      # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install ExpressVPN
      run: |
        sudo dpkg -i expressvpn_2.3.4-1_amd64.deb
        sudo pip install expressvpn-python

    - name: Activate ExpressVPN
      run: expressvpn activate
      env:
        EXPRESSVPN_ACTIVATION_CODE: ${{ secrets.EXPRESSVPN_ACTIVATION_CODE }}
      # Note: You'll need to manually handle the activation step or find a workaround for automation.

    - name: Set ExpressVPN preferences
      run: |
        expressvpn preferences set send_diagnostics false

    - name: Connect to Ireland server via ExpressVPN
      run: expressvpn connect ie

    - name: Configure playwright
      run: playwright install

    - name: Run tests
      if: "github.event.inputs.deployment_target == 'Run tests'"
      run: pytest test_tr_smoke.py

