name: TR_Smoke

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Run tests
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

      # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download ExpressVPN installer
      run: |
        wget https://www.expressvpn.works/clients/linux/expressvpn_3.10.0.74-1_arm64.deb
        # Replace the URL with the correct one for your architecture if necessary
    
    - name: Install ExpressVPN
      run: |
        sudo dpkg -i expressvpn_3.10.0.74-1_arm64.deb
        sudo apt-get install -f

    - name: Activate ExpressVPN
      run: expressvpn activate
      env:
        EXPRESSVPN_ACTIVATION_CODE: ${{ secrets.EXPRESSVPN_ACTIVATION_CODE }}
      # Note: You'll need to manually handle the activation step or find a workaround for automation.

    - name: Connect to ExpressVPN Ireland
      run: |
        expressvpn activate
        expressvpn preferences set send_diagnostics false
        expressvpn connect ireland

    - name: Configure playwright
      run: playwright install

    - name: Run tests
      if: "github.event.inputs.deployment_target == 'Run tests'"
      run: pytest test_tr_smoke.py

