name: Python_CI

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run tests with Pytest
      run: pytest

    - name: Generate Allure report
      run: |
        # Assuming you have allure commandline installed and configured
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report-${{ github.run_number }}-${{ github.run_attempt }}-${{ format(github.event.timestamp, 'yyyy-MM-dd-HH-mm-ss') }}
        path: allure-report


    - name: Notify Telegram about test completion
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        REPORT_URL="<Rustemator.github.io>"
        MESSAGE="Test execution completed. Check the Allure report: $REPORT_URL"
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d chat_id=$TELEGRAM_CHAT_ID -d text="$MESSAGE"